title: Test Website
author: Steven Nim
email: i am not giving you my email lmao
description: > # this means to ignore newlines until "baseurl:"
  Based? Based on what?

# social links
twitter_username: twitter sucks # DO NOT include the @ character, or else the build will fail!
github_username:  check the domain name # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
